apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - nas-storage-class.yaml

helmCharts:
- name: csi-driver-nfs
  version: "v4.8.0"
  repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
  releaseName: csi-driver-nfs
  valuesFile: values.yaml