apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-csi-retain
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.10.17
  share: /volume2/fauli-cluster
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.0
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-csi-delete
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.10.17
  share: /volume2/fauli-cluster
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.0
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-csi-postgres
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.10.17
  share: /volume2/fauli-cluster-no-mapping
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.0
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-csi-retain-keep-permissions
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.10.17
  share: /volume2/fauli-cluster-no-mapping
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.0
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-csi-delete-keep-permissions
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.10.17
  share: /volume2/fauli-cluster-no-mapping
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.0  
