apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: prometheus

helmCharts:
- name: kube-prometheus-stack
  version: "61.6.1"
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  valuesFile: values.yaml