apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crds/crd-alertmanagerconfigs.yaml
  - crds/crd-alertmanagers.yaml
  - crds/crd-podmonitors.yaml
  - crds/crd-probes.yaml
  - crds/crd-prometheusagents.yaml
  - crds/crd-prometheuses.yaml
  - crds/crd-prometheusrules.yaml
  - crds/crd-scrapeconfigs.yaml
  - crds/crd-servicemonitors.yaml
  - crds/crd-thanosrulers.yaml

namespace: prometheus

helmCharts:
- name: kube-prometheus-stack
  version: "61.6.1"
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: kube-prometheus-stack
  valuesFile: values.yaml