apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: ingress-nginx


helmCharts:
- name: ingress-nginx
  version: "4.11.1"
  repo: https://kubernetes.github.io/ingress-nginx
  releaseName: ingress-nginx
  valuesFile: values.yaml