kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "fauli-cluster"
  namespace: "fauli-database"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "16"
  numberOfInstances: 1
  volume:
    size: "64Gi"
    storageClass: "synology-nfs-csi-retain"
  users:
    jellyfin: []
    babybuddy: []
    rocketchat: []
    kanboard: []
  databases:
    jellyfin: jellyfin
    babybuddy: babybuddy
    rocketchat: rocketchat
    kanboard: kanboard
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 2048Mi
    limits:
      cpu: 1000m
      memory: 4096Mi