apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crds/operatorconfigurations.yaml
  - crds/postgresqls.yaml
  - crds/postgresteams.yaml

namespace: postgres

helmCharts:
- name: postgres-operator
  version: "1.12.2"
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  releaseName: postgres-operator
  valuesFile: values.yaml