apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: loki

helmCharts:
- name: loki-stack
  version: "2.10.2"
  repo: https://grafana.github.io/helm-charts
  releaseName: loki-stack
  valuesFile: values.yaml