apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: loki

helmCharts:
- name: loki
  version: "6.10.0"
  repo: https://grafana.github.io/helm-charts
  releaseName: loki
  valuesFile: loki-values.yaml
- name: promtail
  version: "6.16.4"
  repo: https://grafana.github.io/helm-charts
  releaseName: promtail
  valuesFile: promtail-values.yaml