ingress:
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    hosts:
      - host: "jackett.fauli"
        paths:
          - path: /
            pathType: Prefix

env:
  # -- Set the container timezone
  TZ: UTC

###############################################################################
# #
# # IMPORTANT NOTE
# #
# # This chart inherits from our common library chart. You can check the default values/options here:
# # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
# #



# image:
#   # -- image repository
#   repository: ghcr.io/k8s-at-home/jackett
#   # @default -- chart.appVersion
#   tag:
#   # -- image pull policy
#   pullPolicy: IfNotPresent

# # -- environment variables. See [image docs](https://docs.linuxserver.io/images/docker-airsonic#environment-variables-e) for more details.
# # @default -- See below
# env:
#   # -- Set the container timezone
#   TZ: UTC

# # -- Configures service settings for the chart.
# # @default -- See values.yaml
# service:
#   main:
#     ports:
#       http:
#         port: 9117

# ingress:
#   # -- Enable and configure ingress settings for the chart under this key.
#   # @default -- See values.yaml
#   main:
#     enabled: false

# # -- Configure persistence settings for the chart under this key.
# # @default -- See values.yaml
# persistence:
#   config:
#     enabled: false

#   torrentblackhole:
#     enabled: false
#     mountPath: /downloads

persistence:
  # -- Default persistence for configuration files.
  # @default -- See below
  config:
    # -- Enables or disables the persistence item
    enabled: true

    # -- Sets the persistence type
    # Valid options are pvc, emptyDir, hostPath, secret, configMap or custom
    type: pvc
    mountPath: /config

    # -- Storage Class for the config volume.
    # If set to `-`, dynamic provisioning is disabled.
    # If set to something else, the given storageClass is used.
    # If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
    # storageClass: synology-nfs-csi-postgres
    # size: 10Gi
    # -- If you want to reuse an existing claim, the name of the existing PVC can be passed here.
    existingClaim: torrent-pvc  # your-claim
    # -- Used in conjunction with `existingClaim`. Specifies a sub-path inside the referenced volume instead of its root
    subPath: jackett # some-subpath
    accessMode: ReadWriteOnce

    # -- Set to true to retain the PVC upon `helm uninstall`
    retain: true
