ingress:
  main:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
    hosts:
      - host: "qbittorrent.fauli"
        paths:
          - path: /
            pathType: Prefix

env:
  # -- Set the container timezone
  TZ: UTC

## Original default values:
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

# image:
#   # -- image repository
#   repository: ghcr.io/k8s-at-home/qbittorrent
#   # @default -- chart.appVersion
#   tag:
#   # -- image pull policy
#   pullPolicy: IfNotPresent

# settings:
#   # -- Enables automatic port configuration at startup
#   # This sets the qbittorrent port to the value of `service.bittorrent.ports.bittorrent.port`.
#   automaticPortSetup: false

# # -- environment variables. See [image docs](https://docs.k8s-at-home.com/our-container-images/configuration/) for more details.
# # @default -- See below
# env:
#   # -- Set the container timezone
#   TZ: UTC

# # -- Configures service settings for the chart.
# # @default -- See values.yaml
# service:
#   main:
#     ports:
#       http:
#         port: 8080
#   bittorrent:
#     enabled: false
#     type: ClusterIP
#     ports:
#       bittorrent:
#         enabled: true
#         port: 6881
#         protocol: TCP
#         targetPort: 6881

# ingress:
#   # -- Enable and configure ingress settings for the chart under this key.
#   # @default -- See values.yaml
#   main:
#     enabled: false

# # -- Configure persistence settings for the chart under this key.
# # @default -- See values.yaml
# persistence:
#   config:
#     enabled: false

#   media:
#     enabled: false
#     mountPath: /media

#   downloads:
#     enabled: false
#     mountPath: /downloads

# metrics:
#   # -- Enable and configure prometheus-qbittorrent-exporter sidecar and Prometheus podMonitor.
#   # @default -- See values.yaml
#   enabled: false
#   serviceMonitor:
#     interval: 15s
#     scrapeTimeout: 5s
#     labels: {}
#   # -- Enable and configure Prometheus Rules for the chart under this key.
#   # @default -- See values.yaml
#   prometheusRule:
#     enabled: false
#     labels: {}
#     # -- Configure additionial rules for the chart under this key.
#     # @default -- See prometheusrules.yaml
#     rules: []
#       # - alert: qBittorrentDown
#       #   annotations:
#       #     description: qBittorrent service is down.
#       #     summary: qBittorrent is down.
#       #   expr: |
#       #     qbittorrent_up == 0
#       #   for: 5m
#       #   labels:
#       #     severity: critical
#   exporter:
#     image:
#       # -- image repository
#       repository: esanchezm/prometheus-qbittorrent-exporter
#       # -- image tag
#       tag: v1.2.0
#       # -- image pull policy
#       pullPolicy: IfNotPresent
#     env:
#       # -- qbittorrent username
#       # update value after configuring qbittorrent
#       user: "admin"
#       # -- qbittorrent password
#       # update value after configuring qbittorrent
#       password: "adminadmin"
#       # -- metrics port
#       port: 9022
#       # -- log level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
#       logLevel: INFO


### T. Settings:

# image:
#   # -- image repository
#   repository: lscr.io/linuxserver/qbittorrent
#   # @default -- chart.appVersion
#   tag: 4.5.4
#   # -- image pull policy
#   pullPolicy: IfNotPresent

# settings:
#   # -- Enables automatic port configuration at startup
#   # This sets the qbittorrent port to the value of service.bittorrent.ports.bittorrent.port.
#   automaticPortSetup: true

# # -- environment variables. See [image docs](https://docs.k8s-at-home.com/our-container-images/configuration/) for more details.
# # @default -- See below
# env:
#   # -- Set the container timezone
#   TZ: UTC

# # -- Configures service settings for the chart.
# # @default -- See values.yaml
# service:
#   main:
#     ports:
#       http:
#         port: 8080
#   bittorrent:
#     enabled: true
#     type: LoadBalancer
#     ports:
#       bittorrent:
#         enabled: true
#         port: 6881
#         protocol: TCP
#         targetPort: 6881
#         nodePort: 31342

# # -- Configure persistence settings for the chart under this key.
# # @default -- See values.yaml
# persistence:
#   config:
#     enabled: true
#     mountPath: /config
#     size: 100Mi

#   download:
#     enabled: true
#     type: pvc
#     accessMode: ReadWriteMany
#     mountPath: /downloads
#     size: 2Ti

# metrics:
#   # -- Enable and configure prometheus-qbittorrent-exporter sidecar and Prometheus podMonitor.
#   # @default -- See values.yaml
#   enabled: true
#   serviceMonitor:
#     interval: 15s
#     scrapeTimeout: 5s
#     labels:
#       release: prometheus-operator
#   # -- Enable and configure Prometheus Rules for the chart under this key.
#   # @default -- See values.yaml
#   prometheusRule:
#     enabled: false
#     labels: {}
#     # -- Configure additionial rules for the chart under this key.
#     # @default -- See prometheusrules.yaml
#     rules:
#       []
#       # - alert: qBittorrentDown
#       #   annotations:
#       #     description: qBittorrent service is down.
#       #     summary: qBittorrent is down.
#       #   expr: |
#       #     qbittorrent_up == 0
#       #   for: 5m
#       #   labels:
#       #     severity: critical
#   exporter:
#     image:
#       # -- image repository
#       repository: ghcr.io/esanchezm/prometheus-qbittorrent-exporter@sha256
#       # -- image tag
#       tag: 4c019f0c9c8f06a119e2a32b8b338843a782045dce94fa0bef9a94b5f80450f8
#       # -- image pull policy
#       pullPolicy: IfNotPresent
#     env:
#       # -- qbittorrent username
#       # update value after configuring qbittorrent
#       user: "admin"
#       # -- qbittorrent password
#       # update value after configuring qbittorrent
#       password: "adminadmin"
#       # -- metrics port
#       port: 9022
#       # -- log level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
#       logLevel: INFO



