apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-pv
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.17
    path: /volume2/fauli-cluster-no-mapping/torrent
  persistentVolumeReclaimPolicy: Retain
  storageClassName: synology-nfs-csi-retain-keep-permissions
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: synology-nfs-csi-retain-keep-permissions