apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crds/sealedsecrets.yaml

namespace: sealed-secrets

helmCharts:
- name: sealed-secrets
  version: "2.16.1"
  repo: https://bitnami-labs.github.io/sealed-secrets/
  releaseName: sealed-secrets
  valuesFile: values.yaml