apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../origin-cert/secret-origin-cert.yaml

namespace: babybuddy

helmCharts:
- name: babybuddy
  version: "2.3.0"
  repo: https://nicholaswilde.github.io/helm-charts/
  releaseName: babybuddy
  valuesFile: values.yaml