apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: babybuddy

helmCharts:
- name: babybuddy
  version: "0.1.8"
  repo: https://nicholaswilde.github.io/helm-charts/
  releaseName: babybuddy
  valuesFile: values.yaml