
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/nicholaswilde/helm-charts/tree/main/charts/common/values.yaml
#

# image:
#   repository: ghcr.io/linuxserver/babybuddy
#   pullPolicy: IfNotPresent
#   tag: "version-v1.9.0"

# See more environment variables in the babybuddy documentation
# https://github.com/linuxserver/docker-babybuddy#parameters
env:
  TZ: "Europe/Zurich"

# service:
#   port:
#     port: 8000

ingress:
  enabled: true
  hosts:
    - host: "baby.fauli"
      paths:
         - path: /
           pathType: Prefix
    - host: "baby.gute-idee.me"
      paths:
         - path: /
           pathType: Prefix

persistence:
  # -- Default persistence for configuration files.
  # @default -- See below
  config:
    # -- Enables or disables the persistence item
    enabled: true

    # -- Sets the persistence type
    # Valid options are pvc, emptyDir, hostPath, secret, configMap or custom
    type: pvc
    mountPath: /config

    # -- Storage Class for the config volume.
    # If set to `-`, dynamic provisioning is disabled.
    # If set to something else, the given storageClass is used.
    # If undefined (the default) or set to null, no storageClassName spec is set, choosing the default provisioner.
    storageClass: synology-nfs-csi-retain
    size: 10Gi

    # -- Set to true to retain the PVC upon `helm uninstall`
    retain: true

# Enable postgres
# https://github.com/nicholaswilde/helm-charts/blob/main/charts/postgres/values.yaml
postgres:
  enabled: false
  secret:
    POSTGRES_PASSWORD: "babybuddy-pass"
  env:
    POSTGRES_USER: "babybuddy"
    POSTGRES_DB: "babybuddy-postgres"
  fullnameOverride: babybuddy-postgres
