apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../origin-cert
  - secret-nextcloud.yaml

namespace: nextcloud

helmCharts:
- name: nextcloud
  version: "5.5.2"
  repo: https://nextcloud.github.io/helm/
  releaseName: nextcloud
  valuesFile: values.yaml