apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-fauli
  namespace: nextcloud  # Ensure this is set to the namespace where your Nextcloud is deployed
type: Opaque
data:
  nextcloud-username: YWRtaW4=             # base64 encoded value of 'admin'
  nextcloud-password: Y2hhbmdlbWU=         # base64 encoded value of 'changeme'