apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: postgres

helmCharts:
- name: postgres-operator-ui
  version: "1.12.2"
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  releaseName: postgres-operator-ui
  valuesFile: values.yaml