apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - recipes-secret-origin-cert.yaml

namespace: tandoor

helmCharts:
- name: tandoor
  version: "0.9.6"
  repo: https://charts.gabe565.com
  releaseName: tandoor
  valuesFile: values.yaml
