apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://www.talos.dev/v1.7/kubernetes-guides/network/deploying-cilium/

resources:
  - namespace.yaml

namespace: cilium

helmCharts:
- name: cilium
  version: "1.16.0"
  repo: https://helm.cilium.io/
  releaseName: cilium
  valuesFile: values.yaml