apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - collab-synth-secret-origin-cert.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: collab-synth
