apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - qreator-secret-origin-cert.yaml

namespace: qreator
helmGlobals:
  chartHome: .
helmCharts:
- name: qreator
  repo: qreator-chart
  releaseName: qreator
  valuesFile: values.yaml