apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: rocketchat

helmCharts:
- name: rocketchat
  version: "6.17.1"
  repo: https://rocketchat.github.io/helm-charts
  releaseName: rocketchat
  valuesFile: values.yaml