apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  # - actual-finnce-secret-origin-cert.yaml

namespace: actual-finance

helmCharts:
- name: actual
  version: "2.0.0"
  repo: https://beluga-cloud.github.io/charts
  releaseName: actual
  valuesFile: values.yaml