apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-finance-pvc
  namespace: actual-finance
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi
  storageClassName: synology-nfs-csi-retain-keep-permissions