apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - jellyfin-secret-origin-cert.yaml

namespace: jellyfin

helmCharts:
- name: jellyfin
  version: "9.5.3"
  repo: https://k8s-at-home.com/charts/
  releaseName: jellyfin
  valuesFile: values.yaml