apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: kanboard

spec:
  destination:
    server: https://kubernetes.default.svc  

helmCharts:
- name: kanboard
  version: "0.1.8"
  repo: https://nicholaswilde.github.io/helm-charts/
  releaseName: kanboard
  valuesFile: values.yaml