apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # - home-assistant-secret-origin-cert.yaml

namespace: home-assistant

helmCharts:
- name: home-assistant
  # version: "0.1.8"
  repo: http://pajikos.github.io/home-assistant-helm-chart/
  releaseName: home-assistant
  valuesFile: values.yaml