# S3 compatible storage
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: minio

helmCharts:
- name: operator
  version: "6.0.2"
  repo: https://operator.min.io
  releaseName: operator
  valuesFile: values.yaml

