apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.13.37.120-10.13.37.140
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: defaul-advertisement
  namespace: metallb-system