apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - ip-pool.yaml

namespace: metallb-system

helmCharts:
- name: metallb
  version: "0.14.8"
  repo: https://metallb.github.io/metallb
  releaseName: metallb
  valuesFile: values.yaml