apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: docker-registry
type: Opaque
data:
  htpasswd: ZmF1bGk6JDJ5JDA1JGVUYzdJSFlIRnovU0ZJSnFmc2hUc09wTy9kZHRqQmpmSFpwVHA5a1RZM0JDcldQQzI2b2hXCgo=