apiVersion: apps/v1
kind: Deployment
metadata:
  name: cells-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cells-app
  template:
    metadata:
      labels:
        app: cells-app
    spec:
      containers:
      - name: cells-app-container
        image: fauli/cells:0.0.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
